### ISSUE TITLE
Преобразовать репозиторий в библиотеку и добавить инструкцию по установке/использованию

### ISSUE THREAD

**Issue by syeysk** [smer44/graph-semantical-engine#2]
Проблема:
- без чтения исходного кода не понятно, как применять модули.

Решение:
- [x] переименовать модуль `ylines_to_objects_by_indents.py` в `graph_semantic_engine/gol.py`
- [x] переименовать модуль `ygraph_to_gui.py`  в `graph_semantic_engine/gui.py`
- [x] в модуль `graph_semantic_engine/gol.py` добавить глобальные функции `dump`, `dumps`, `load`, `loads`  (по аналогии с модулями `json`, `yaml`, `pickle`)
- [ ] добавить файлы `requirements.txt` (пустой), `setup.py`, `pyproject.toml`, котрые содержат в том числе и настройки для запуска GUI из консоли и импорта модулей для встраивания парсера и canvas-виджета в сторонние приложения.
- [ ] в `README.md` добавить инструкции по установке и использованию библиотеке
- [ ] в `examples` положить примеры использования библотеки

**Comment by smer44** [comment]
а что в pyproject.toml?

**Comment by smer44** [comment]
а ещё надо добавить альтернативный формат когда граф задаётся строками
child : parent
или 
child: parent1 , parent2..

вообщем в GOL будет несколько модусов формата

**Comment by syeysk** [comment]
> а что в pyproject.toml?

Описание библиотеки для автоматической установки через и запуска GUI из консоли. Современный аналог `setup.py`. Я сделаю.
